### ISSUE TITLE
ported to Node.JS

### ISSUE THREAD

**Issue by vicapow** [LazarSoft/jsqrcode#3]
Hey. Just wanted to let you know I made a port of this module that'll work in Node.JS

https://github.com/vicapow/jsqrcode

**Comment by dibeesh** [comment]
It's not working for by running the test.js file under example folder giving error


unable to read qr code TypeError: Right-hand side of 'instanceof' is not callable
    at isCanvas (/home/dibeesh/koa/pushtest/jsqrcode/examples/node/src/qrcode.js:54:23)
    at Object.qrcode.decode (/home/dibeesh/koa/pushtest/jsqrcode/examples/node/src/qrcode.js:84:9)
    at image.onload (/home/dibeesh/koa/pushtest/jsqrcode/examples/node/test.js:12:21)
    at setSource (/home/dibeesh/koa/pushtest/jsqrcode/node_modules/canvas/lib/image.js:102:14)
    at Image.set (/home/dibeesh/koa/pushtest/jsqrcode/node_modules/canvas/lib/image.js:65:9)
    at Object.<anonymous> (/home/dibeesh/koa/pushtest/jsqrcode/examples/node/test.js:18:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
